const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');const {ambiente,read,clone,exemplo,preparar,cartao,avancar}=require('./apoio.cjs');
function datasetContext(file){let result;const ctx=vm.createContext({ConstraintType:{MUST:1},DatasetBuilder:{newDataset(){result={columns:[],rows:[],addColumn(c){this.columns.push(c);},addRow(r){this.rows.push(r);}};return result;}}});vm.runInContext(read('datasets/'+file+'.js'),ctx);return ctx;}
for(const name of ['Clientes','Areas','Pessoas','Veiculos','Condutores','Servicos'])test('Dataset novo '+name+': catálogo e filtros exatos',()=>{const c=datasetContext('dsMobilidade'+name),all=c.createDataset(null,null,null);assert.ok(all.rows.length>0);const field=all.columns[0],value=all.rows[0][0],exact={fieldName:field,initialValue:value,finalValue:value,constraintType:1};assert.ok(c.createDataset(null,[exact],null).rows.length>0);for(const patch of [{fieldName:'desconhecido'},{initialValue:'inexistente',finalValue:'inexistente'},{finalValue:'outro'},{constraintType:2},{likeSearch:true}])assert.equal(c.createDataset(null,[{...exact,...patch}],null).rows.length,0);});
function formulario(c,e,mode='MOD'){const {values,indices}=cartao(c,e);return {values,enabled:{},getFormMode:()=>mode,getValue:k=>values[k]||'',setValue(k,v){values[k]=v;},getChildrenIndexes:k=>indices[k]||[],setEnabled(k,v){this.enabled[k]=v;},setEnhancedSecurityHiddenInputs(v){this.security=v;}};}
test('enableFields bloqueia campos de outras etapas e índices com lacunas',()=>{const c=ambiente({getValue:k=>k==='WKNumState'?1300:1}),e=exemplo(c),f=formulario(c,e);vm.runInContext(read('scripts/templates/enableFields.js'),c);c.enableFields(f);assert.equal(f.security,true);assert.equal(f.enabled.tipoViagem,false);assert.equal(f.enabled.acaoCotacao,true);assert.equal(f.enabled.valorCotadoServico___2,true);assert.equal(f.enabled.referenciaCotacao___6,true);assert.equal(f.enabled.nomeServico___2,false);assert.equal(f.enabled.identificadorParticipante___4,false);assert.equal(f.enabled.assinaturaLiberacao,false);});
test('enableFields permite documentos internacionais à logística e bloqueia VIEW',()=>{const c=ambiente({getValue:k=>k==='WKNumState'?1600:1}),e=exemplo(c),f=formulario(c,e);vm.runInContext(read('scripts/templates/enableFields.js'),c);c.enableFields(f);assert.equal(f.enabled.situacaoDocumentacaoViagem,true);assert.equal(f.enabled.referenciaDocumentacaoViagem,true);const view=formulario(c,e,'VIEW');c.enableFields(view);assert.ok(Object.values(view.enabled).every(v=>v===false));});
test('Servidor lê tabelas com lacunas sem pressupor índices contíguos',()=>{const c=ambiente(),e=exemplo(c),f=formulario(c,e),ctx=c.MobilidadeServidor.ler(f.getValue,f.getChildrenIndexes);assert.deepEqual(Array.from(ctx.tabelas.participantes,p=>p.__indice),['1','4']);assert.deepEqual(Array.from(ctx.tabelas.servicos,p=>p.__indice),['2','6']);assert.equal(ctx.dados.tipoViagem,'cidade');});
test('validateForm identifica responsável real e calcula liberação sem confiar no valor recebido',()=>{let code=1800;const c=ambiente({getValue:k=>k==='WKNumState'?code:42,fluigAPI:{getUserService:()=>({getCurrent:()=>({getFullName:()=> 'Responsável autenticado'})})},ConstraintType:{MUST:1},DatasetFactory:{createConstraint:(fieldName,initialValue,finalValue,constraintType)=>({fieldName,initialValue,finalValue,constraintType}),getDataset:()=>({rowsCount:1})}}),e=exemplo(c);preparar(c,e,1800);e.dados.assinaturaLiberacao='FORJADA';const f=formulario(c,e);vm.runInContext(read('scripts/templates/validateForm.js'),c);c.validateForm(f);assert.equal(f.values.assinaturaLiberacao,c.MobilidadeRegras.assinatura(e.dados,e.tabelas));assert.equal(f.values.responsavelUltimaAcao,'Responsável autenticado');assert.equal(f.values.destinoMobilidade,'1850');f.values.inspecao_freios='naoConforme';assert.throws(()=>c.validateForm(f),/bloqueada/);});
test('validateForm bloqueia referência ausente no dataset e não altera consulta',()=>{const c=ambiente({getValue:k=>k==='WKNumState'?1100:42,fluigAPI:{getUserService:()=>({getCurrent:()=>({getFullName:()=> 'Responsável'})})},ConstraintType:{MUST:1},DatasetFactory:{createConstraint:()=>({}),getDataset:()=>({rowsCount:0})}}),e=exemplo(c),f=formulario(c,e);vm.runInContext(read('scripts/templates/validateForm.js'),c);assert.throws(()=>c.validateForm(f),/Referência/);const view=formulario(c,e,'VIEW');c.validateForm(view);assert.equal(view.values.responsavelUltimaAcao,undefined);});
function mapaJava(values){const keys=Object.keys(values);return {get:k=>values[k]||'',keySet:()=>({iterator(){let i=0;return {hasNext:()=>i<keys.length,next:()=>keys[i++]};}})};}
test('Condições do processo leem Java Map e usam o mesmo destino do domínio',()=>{const base=ambiente(),e=exemplo(base);preparar(base,e,1200);const {values}=cartao(base,e),c=ambiente({getValue:k=>k==='WKNumState'?1200:42,hAPI:{getCardData:()=>mapaJava(values)}});vm.runInContext(read('scripts/templates/processo.js'),c);assert.equal(c.MobilidadeProcesso.podeSeguir(1200,1300),true);assert.equal(c.MobilidadeProcesso.podeSeguir(1200,1400),false);assert.deepEqual(Array.from(c.MobilidadeProcesso.contexto().tabelas.participantes,p=>p.__indice),['1','4']);});
test('beforeTaskSave rejeita destino incorreto e aceita gateway configurado',()=>{const base=ambiente(),e=exemplo(base);preparar(base,e,1800);avancar(base,e,1800);preparar(base,e,1850);const {values}=cartao(base,e);let code=1850;const c=ambiente({getValue:k=>k==='WKNumState'?code:42,hAPI:{getCardData:()=>mapaJava(values)}});vm.runInContext(read('scripts/templates/processo.js')+read('scripts/templates/beforeTaskSave.js'),c);c.beforeTaskSave('id',1900,[]);assert.throws(()=>c.beforeTaskSave('id',1950,[]),/Destino/);code=1800;c.beforeTaskSave('id',1801,[]);values.inspecao_freios='naoConforme';assert.throws(()=>c.beforeTaskSave('id',1801,[]),/bloqueada/);code=1100;c.beforeTaskSave('id',1200,[]);});
test('beforeSendValidate usa validação compartilhada, bloqueia VIEW e destinos incoerentes',()=>{const c=ambiente({document:{addEventListener(){}},MobilidadeContexto:{atividade:1800,modo:'EDIT'}}),e=exemplo(c);preparar(c,e,1800);vm.runInContext(read('formulario/js/interfaceMobilidade.js'),c);c.dadosMob=()=>e.dados;c.tabelasMob=()=>e.tabelas;c.hojeMob=()=>e.hoje;assert.equal(c.beforeSendValidate(1800,1850),true);assert.throws(()=>c.beforeSendValidate(1800,1950),/incompatível/);e.dados.inspecao_freios='naoConforme';assert.throws(()=>c.beforeSendValidate(1800,1850),/bloqueada/);e.dados.inspecao_freios='conforme';c.MobilidadeContexto.modo='VIEW';assert.throws(()=>c.beforeSendValidate(1800,1850),/consulta/i);});

test('Regularização permite ao servidor persistir o reset da inspeção com proteção ativa',()=>{const c=ambiente({getValue:k=>k==='WKNumState'?1810:42}),e=exemplo(c),f=formulario(c,e);vm.runInContext(read('scripts/templates/enableFields.js'),c);c.enableFields(f);assert.equal(f.enabled.situacaoLiberacaoVeiculo,true);assert.equal(f.enabled.aceiteNormativo,true);assert.equal(f.enabled.inspecao_freios,true);assert.equal(f.enabled.assinaturaLiberacao,true);assert.equal(f.enabled.valorAdiantamento,false);});

test('Índices de tabela também aceitam lista Java sem métodos de Array',()=>{const c=ambiente(),lista={size:()=>2,get:i=>[2,7][i]};assert.deepEqual(Array.from(c.MobilidadeServidor.indicesForm({getChildrenIndexes:()=>lista},'tabela')),['2','7']);});
