const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const root=path.join(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
function ambiente(extra={},files=['formulario/js/configuracao.js','formulario/js/regrasMobilidade.js','scripts/templates/servidor.js']){const ctx=vm.createContext({...extra});files.forEach(p=>vm.runInContext(read(p),ctx,{filename:p}));return ctx;}
const clone=o=>JSON.parse(JSON.stringify(o));
function exemplo(ctx,tipo='cidade'){const cfg=ctx.MobilidadeConfig,hoje=ctx.MobilidadeServidor.hoje();const d={tipoViagem:tipo,codigoClienteOrigem:'MOB-ALFA',codigoAreaAdministrativa:'MOB-ALFA-1',identificadorSolicitante:'MOB-PESSOA-1',identificadorBeneficiario:'MOB-PESSOA-1',contatoSolicitante:'Fictício',finalidadeViagem:'Visita fictícia',origemViagem:'São Paulo',destinoViagem:tipo==='cidade'?'São Paulo':tipo==='nacional'?'Campinas':'Lisboa',paisOrigem:'BR',paisDestino:tipo==='internacional'?'PT':'BR',inicioPrevisto:hoje+'T00:00',fimPrevisto:hoje+'T23:59',codigoCentroCusto:'MOB-CUSTO',moedaProcesso:tipo==='internacional'?'USD':'BRL',taxaCambio:tipo==='internacional'?'5':'1',valorAdiantamento:tipo==='cidade'?'0':'500',modalidadeVeiculo:tipo==='cidade'?'corporativo':'locado',codigoVeiculo:tipo==='cidade'?'MOB-VEICULO-1':'MOB-VEICULO-2',identificadorCondutor:'MOB-CONDUTOR-1',paisUsoVeiculo:tipo==='internacional'?'PT':'BR',contatoEmergencia:'Contato fictício',acaoPlanejamento:'enviar'};
const t={participantes:cfg.dados.pessoas.filter(p=>p.codigoClienteOrigem==='MOB-ALFA').map((p,i)=>({identificadorParticipante:p.identificadorColaborador,nomeParticipante:p.nomeColaborador,emailParticipante:p.emailColaborador,__indice:String(i*3+1)})),servicos:[],despesas:[],abastecimentos:[]};
(tipo==='cidade'?['combustivel','pedagio']:['aereo','hotel','locacao']).forEach((code,i)=>{let s={codigoServico:code,inicioServico:d.inicioPrevisto,fimServico:d.fimPrevisto,quantidadeServico:'1',valorPrevistoServico:tipo==='cidade'?'100':tipo==='internacional'?['3000','600','400'][i]:['1200','900','400'][i],detalhesServico:'Fictício',trechoOrigem:'A',trechoDestino:'B',horarioPreferencial:'Manhã',bagagem:'Uma mala',cidadeHotel:'Destino',quartos:'1',localRetirada:'A',localDevolucao:'B',categoriaCarro:'Automóvel'};s=ctx.MobilidadeRegras.validarServico(s,d,cfg);s.__indice=String(i*4+2);s.situacaoServico='pendente';t.servicos.push(s);});return {dados:d,tabelas:t,hoje};}
function preparar(ctx,ex,code){const d=ex.dados,t=ex.tabelas,cfg=ctx.MobilidadeConfig,e=ctx.MobilidadeRegras.etapa(code,cfg),now=ex.hoje+'T12:00';
if([1200,1400,1500,1550].includes(code))d[e.campoDecisao]='aprovado';
if(code===1300){d.acaoCotacao='concluir';t.servicos.forEach(s=>{s.valorCotadoServico=s.valorPrevistoServico;s.referenciaCotacao='REF-COTACAO';});}
if(code===1600){d.acaoOrganizacao='concluir';t.servicos.forEach(s=>{s.situacaoServico='confirmado';s.referenciaServico='REF-RESERVA';});Object.assign(d,{situacaoDocumentacaoViagem:'conferida',referenciaDocumentacaoViagem:'REF-DOC',conferenciaRegrasDestino:'sim',referenciaRegrasDestino:'REF-LOCAL'});}
if(code===1700)Object.assign(d,{situacaoAdiantamento:'liberado',valorAdiantamentoLiberado:d.valorAdiantamento,dataTransferencia:ex.hoje,referenciaTransferencia:'REF-TRANSFERENCIA'});
if(code===1800){cfg.seguranca.itens.forEach(c=>d['inspecao_'+c.codigo]='conforme');Object.assign(d,{situacaoLiberacaoVeiculo:'liberado',aceiteNormativo:'sim',nivelCombustivelSaida:'100',odometroInspecao:'10000',observacaoInspecao:'Fictício'});}
if(code===1810)Object.assign(d,{referenciaRegularizacao:'REF-REGULARIZACAO',observacaoRegularizacao:'Correção fictícia'});
if(code===1850)Object.assign(d,{dataHoraSaida:now,odometroSaida:'10000',confirmacaoCondutor:'sim'});
if(code===1900){Object.assign(d,{dataHoraRetorno:ex.hoje+'T13:00',odometroRetorno:'10100',nivelCombustivelRetorno:'50',observacaoRetorno:'Fictício'});cfg.seguranca.itens.forEach(c=>d['retorno_'+c.codigo]='conforme');}
if(code===1910){const v=cfg.dados.veiculos.find(v=>v.codigoVeiculo===d.codigoVeiculo);Object.assign(d,{situacaoAbastecimento:'abastecido',nivelCombustivelRegularizado:v.nivelReferenciaRetorno,observacaoAbastecimento:'Fictício'});t.abastecimentos=[{__indice:'9',dataHoraAbastecimento:ex.hoje+'T13:01',odometroAbastecimento:'10101',tipoCombustivel:v.tipoCombustivel,litros:'10.000',valorAbastecimento:'60',postoAbastecimento:'Fictício',referenciaAbastecimento:'REF-COMBUSTIVEL'}];}
if(code===1920)d.situacaoDevolucao='disponivel';
if(code===1930){Object.assign(d,{referenciaManutencao:'REF-MANUTENCAO',observacaoManutencao:'Correção fictícia'});cfg.seguranca.itens.forEach(c=>d['retorno_'+c.codigo]='conforme');}
if(code===1950){d.observacaoContas='Fictício';t.despesas=[{__indice:'12',categoriaDespesa:'alimentacao',dataDespesa:ex.hoje,descricaoDespesa:'Fictício',valorDespesa:'80',formaCusteio:'colaborador',referenciaComprovante:'REF-DESPESA'}];}
if(code===2000)Object.assign(d,{situacaoConferencia:'aprovado',referenciaAcerto:'REF-ACERTO'});
if(code===2090){Object.assign(d,{motivoCancelamento:'Fictício',referenciaCancelamento:'REF-CANCELAMENTO'});t.servicos.forEach(s=>{s.situacaoServico='cancelado';s.referenciaServico='REF-CANCELAMENTO';});}
}
function aplicar(ctx,ex,code){return ctx.MobilidadeServidor.atualizar(code,ex,(k,v)=>{if(k.includes('___')){const [nome,i]=k.split('___');const key=Object.keys(ctx.MobilidadeConfig.tabelas).find(k=>ctx.MobilidadeConfig.tabelas[k].campos.includes(nome));ex.tabelas[key].find(s=>s.__indice===i)[nome]=String(v);}else ex.dados[k]=String(v);});}
function avancar(ctx,ex,code){ctx.MobilidadeRegras.validar(code,ex.dados,ex.tabelas,ctx.MobilidadeConfig,ex.hoje);return aplicar(ctx,ex,code);}
function cartao(ctx,ex){const values={...ex.dados},indices={};Object.entries(ctx.MobilidadeConfig.tabelas).forEach(([key,s])=>{indices[s.nome]=ex.tabelas[key].map(r=>r.__indice);ex.tabelas[key].forEach(r=>s.campos.forEach(k=>values[k+'___'+r.__indice]=r[k]||''));});return {values,indices};}
module.exports={read,ambiente,clone,exemplo,preparar,aplicar,avancar,cartao};
