/* Adaptadores locais. Não persistem dados nem acionam serviços externos. */
var MobilidadeContexto={atividade:1100,modo:'EDIT'},ConstraintType={MUST:1};
var DatasetFactory={createConstraint:function(fieldName,initialValue,finalValue,constraintType){return {fieldName:fieldName,initialValue:initialValue,finalValue:finalValue,constraintType:constraintType};},getDataset:function(name,fields,constraints,sortFields){if(!CatalogosMobilidade[name])throw new Error('Dataset não disponível.');var builder={newDataset:function(){return {columns:[],values:[],rowsCount:0,addColumn:function(c){this.columns.push(c);},addRow:function(r){var o={};this.columns.forEach(function(c,i){o[c]=r[i];});this.values.push(o);this.rowsCount++;},getValue:function(i,c){return this.values[i][c];}};}};return CatalogosMobilidade[name](builder,fields,constraints,sortFields);}};
var DemoMobilidade={indice:0,atividade:1100,inspecao:false,selecionada:1100,trilha:[]};
function wdkAddChild(tableName){var table=campoMob(tableName),row=table.querySelector('tbody tr').cloneNode(true),idx=++DemoMobilidade.indice;row.querySelectorAll('input,textarea,select').forEach(function(el){if(el.id)el.id+='___'+idx;if(el.name)el.name+='___'+idx;el.value='';});row.classList.add('mob-linha');table.querySelector('tbody').appendChild(row);return idx;}
function fnWdkRemoveChild(el){el.closest('tr').remove();}
function instanteDemoMob(){var d=new Date();return hojeMob()+'T'+('0'+d.getHours()).slice(-2)+':'+('0'+d.getMinutes()).slice(-2);}
function abaDemoMob(name){var panels={apresentacao:'abaApresentacao',bpmn:'abaBpmn',tecnico:'abaTecnico'};Object.keys(panels).forEach(function(k){campoMob(panels[k]).hidden=k!==name;});campoMob('paginaMobilidade').hidden=name!=='formulario';campoMob('acoesDemo').hidden=name!=='formulario'&&name!=='bpmn';document.querySelectorAll('[data-aba]').forEach(function(b){b.setAttribute('aria-selected',String(b.dataset.aba===name));});if(name==='tecnico')tecnicoDemoMob();}
function etapaDemoMob(code,inspecao){code=Number(code);MobilidadeContexto.atividade=code;MobilidadeContexto.modo=[2100,2180,2190].indexOf(code)>=0?'VIEW':'EDIT';DemoMobilidade.inspecao=Boolean(inspecao);if(!inspecao)DemoMobilidade.atividade=code;atualizarTelaMob();var e;try{e=MobilidadeRegras.etapa(code,MobilidadeConfig);}catch(x){e={nome:code===2100?'Concluído':code===2180?'Cancelado':'Recusado',papel:'Consulta'};}campoMob('etapaAtualDemo').textContent=(inspecao?'Inspeção livre: ':'Simulação: ')+code+' · '+e.nome;atualizarModeloMob();}
function atualizarModeloMob(){document.querySelectorAll('.mob-node').forEach(function(n){n.classList.toggle('is-current',Number(n.dataset.atividade)===DemoMobilidade.atividade);n.classList.toggle('is-executed',DemoMobilidade.trilha.some(function(t){return t.origem===Number(n.dataset.atividade)||t.destino===Number(n.dataset.atividade);}));});document.querySelectorAll('.mob-edge').forEach(function(n){n.classList.toggle('is-executed',DemoMobilidade.trilha.some(function(t){return t.origem===Number(n.dataset.origem)&&t.destino===Number(n.dataset.destino);}));});campoMob('trilhaMob').textContent=DemoMobilidade.trilha.map(function(t){return '#'+t.origem+' → #'+t.destino;}).join('\n')||'Nenhuma transição executada.';}
function inspecionarDemoMob(code){code=Number(code);var e;try{e=MobilidadeRegras.etapa(code,MobilidadeConfig);}catch(x){return;}DemoMobilidade.selecionada=e.codigo;definirMob('inspecionarEtapaMob',e.codigo);campoMob('tituloInspectorMob').textContent='#'+e.codigo+' · '+e.nome;campoMob('papelInspectorMob').textContent='Papel: '+e.papel;campoMob('decisaoInspectorMob').textContent='Campo de decisão: '+(e.campoDecisao||'Conclusão da atividade');var ul=campoMob('rotasInspectorMob');ul.replaceChildren();e.rotas.forEach(function(r){var li=document.createElement('li');li.textContent=r.valor+' → '+r.destino+(r.quando==='sempre'?'':' ('+r.quando+')');ul.appendChild(li);});}
function reiniciarDemoMob(){campoMob('formMobilidade').reset();Object.keys(MobilidadeConfig.tabelas).forEach(function(k){linhasMob(k).forEach(function(r){r.remove();});});MobilidadeServidor.campos().forEach(function(k){definirMob(k,'');});MobilidadeConfig.seguranca.itens.forEach(function(c){definirMob('inspecao_'+c.codigo,'');definirMob('retorno_'+c.codigo,'');});DemoMobilidade.trilha=[];definirMob('moedaProcesso','BRL');definirMob('taxaCambio','1');definirMob('valorAdiantamento','0');definirMob('modalidadeVeiculo','nenhum');definirMob('dataAbertura',hojeMob());definirMob('numeroProcesso','MOB-DEMO-001');atualizarCatalogosMob();etapaDemoMob(1100,false);inspecionarDemoMob(1100);avisoMob('Demonstração reiniciada. Nenhuma operação real é realizada.');}
function carregarDemoMob(){
 reiniciarDemoMob();var type=valorMob('tipoExemploMob'),cliente=MobilidadeConfig.dados.clientes[0].codigoClienteOrigem;
 definirMob('tipoViagem',type);definirMob('codigoClienteOrigem',cliente);definirMob('modalidadeVeiculo',type==='cidade'?'corporativo':'locado');atualizarCatalogosMob();
 var d={codigoAreaAdministrativa:'MOB-ALFA-1',identificadorSolicitante:'MOB-PESSOA-1',identificadorBeneficiario:'MOB-PESSOA-1',contatoSolicitante:'Contato demonstrativo',finalidadeViagem:'Visita técnica fictícia',origemViagem:'São Paulo',destinoViagem:type==='cidade'?'São Paulo':type==='nacional'?'Campinas':'Lisboa',paisOrigem:'BR',paisDestino:type==='internacional'?'PT':'BR',inicioPrevisto:hojeMob()+'T00:00',fimPrevisto:hojeMob()+'T23:59',codigoCentroCusto:'MOB-CUSTO-DEMO',moedaProcesso:type==='internacional'?'USD':'BRL',taxaCambio:type==='internacional'?'5':'1',valorAdiantamento:type==='cidade'?'0':type==='nacional'?'500':'700',codigoVeiculo:type==='cidade'?'MOB-VEICULO-1':'MOB-VEICULO-2',identificadorCondutor:'MOB-CONDUTOR-1',paisUsoVeiculo:type==='internacional'?'PT':'BR',contatoEmergencia:'Contato fictício de emergência',acaoPlanejamento:'enviar'};
 Object.keys(d).forEach(function(k){definirMob(k,d[k]);});
 MobilidadeConfig.dados.pessoas.filter(function(p){return p.codigoClienteOrigem===cliente;}).forEach(function(p){criarLinhaMob('participantes',{identificadorParticipante:p.identificadorColaborador,nomeParticipante:p.nomeColaborador,emailParticipante:p.emailColaborador});});
 var cats=type==='cidade'?['combustivel','pedagio']:['aereo','hotel','locacao'];cats.forEach(function(code,i){var s={codigoServico:code,inicioServico:d.inicioPrevisto,fimServico:d.fimPrevisto,quantidadeServico:'1',valorPrevistoServico:type==='cidade'?(i===0?'120':'20'):type==='nacional'?['1200','900','400'][i]:['3000','600','400'][i],detalhesServico:'Serviço fictício para demonstração',trechoOrigem:d.origemViagem,trechoDestino:d.destinoViagem,horarioPreferencial:'Conforme agenda demonstrativa',bagagem:'Uma mala demonstrativa',cidadeHotel:d.destinoViagem,quartos:'1',localRetirada:'Local fictício A',localDevolucao:'Local fictício B',categoriaCarro:'Automóvel demonstrativo'};var clean=MobilidadeRegras.validarServico(s,d,MobilidadeConfig);clean.situacaoServico='pendente';criarLinhaMob('servicos',clean);});
 atualizarTelaMob();avisoMob('Exemplo '+type+' carregado. Valores e cotação são fictícios. Preencha ou simule cada etapa.');
}
function prepararDemoMob(){
 if(DemoMobilidade.inspecao){avisoMob('A inspeção livre não executa o processo. Carregue um exemplo para simular a sequência.');return;}
 var code=codigoMob(),d=dadosMob(),t=tabelasMob();
 var fill=function(values){Object.keys(values).forEach(function(k){definirMob(k,values[k]);});};
 if([1200,1400,1500,1550].indexOf(code)>=0){var e=MobilidadeRegras.etapa(code,MobilidadeConfig);definirMob(e.campoDecisao,'aprovado');}
 if(code===1300){t.servicos.forEach(function(s){definirMob('valorCotadoServico___'+s.__indice,s.valorPrevistoServico);definirMob('referenciaCotacao___'+s.__indice,'COTAÇÃO-FICTÍCIA-'+s.__indice);});definirMob('acaoCotacao','concluir');}
 if(code===1600){t.servicos.forEach(function(s){definirMob('situacaoServico___'+s.__indice,'confirmado');definirMob('referenciaServico___'+s.__indice,'RESERVA-FICTÍCIA-'+s.__indice);});fill({acaoOrganizacao:'concluir',situacaoDocumentacaoViagem:'conferida',referenciaDocumentacaoViagem:'Conferência fictícia de documentos',conferenciaRegrasDestino:'sim',referenciaRegrasDestino:'Conferência fictícia de regras do destino'});}
 if(code===1700)fill({valorAdiantamentoLiberado:d.valorAdiantamento,referenciaTransferencia:'TRANSFERÊNCIA-FICTÍCIA',dataTransferencia:hojeMob(),situacaoAdiantamento:'liberado'});
 if(code===1800){MobilidadeConfig.seguranca.itens.forEach(function(c){definirMob('inspecao_'+c.codigo,'conforme');});fill({nivelCombustivelSaida:'100',odometroInspecao:'10000',aceiteNormativo:'sim',situacaoLiberacaoVeiculo:'liberado',observacaoInspecao:'Inspeção inteiramente fictícia. Não autoriza circulação real.'});}
 if(code===1810)fill({referenciaRegularizacao:'CORREÇÃO-FICTÍCIA',observacaoRegularizacao:'Regularização demonstrativa. Será exigida nova inspeção.'});
 if(code===1850)fill({dataHoraSaida:instanteDemoMob(),odometroSaida:'10000',confirmacaoCondutor:'sim',observacaoSaida:'Confirmação fictícia do condutor'});
 if(code===1900){fill({dataHoraRetorno:instanteDemoMob(),odometroRetorno:'10100',nivelCombustivelRetorno:'50',observacaoRetorno:'Retorno fictício'});MobilidadeConfig.seguranca.itens.forEach(function(c){definirMob('retorno_'+c.codigo,'conforme');});}
 if(code===1910){var v=MobilidadeRegras.referencia(MobilidadeConfig.dados.veiculos,'codigoVeiculo',d.codigoVeiculo,d.codigoClienteOrigem);fill({situacaoAbastecimento:'abastecido',nivelCombustivelRegularizado:v.nivelReferenciaRetorno,observacaoAbastecimento:'Abastecimento fictício conforme referência de devolução'});if(!t.abastecimentos.length)criarLinhaMob('abastecimentos',{dataHoraAbastecimento:instanteDemoMob(),odometroAbastecimento:'10100',tipoCombustivel:v.tipoCombustivel,litros:'10.000',valorAbastecimento:d.moedaProcesso==='BRL'?'60':'12',postoAbastecimento:'Posto fictício',referenciaAbastecimento:'COMPROVANTE-FICTÍCIO-ABASTECIMENTO'});}
 if(code===1920)fill({situacaoDevolucao:'disponivel'});
 if(code===1930){fill({referenciaManutencao:'MANUTENÇÃO-FICTÍCIA',observacaoManutencao:'Regularização demonstrativa após retorno'});MobilidadeConfig.seguranca.itens.forEach(function(c){definirMob('retorno_'+c.codigo,'conforme');});}
 if(code===1950){if(!t.despesas.length)criarLinhaMob('despesas',{categoriaDespesa:'alimentacao',dataDespesa:hojeMob(),descricaoDespesa:'Despesa demonstrativa do beneficiário',valorDespesa:d.moedaProcesso==='BRL'?'80':'100',formaCusteio:'colaborador',referenciaComprovante:'COMPROVANTE-FICTÍCIO-DESPESA'});fill({observacaoContas:'Prestação de contas fictícia. Abastecimento só integra o acerto se incluído como despesa, uma única vez.'});}
 if(code===2000)fill({situacaoConferencia:'aprovado',referenciaAcerto:'ACERTO-FICTÍCIO',observacaoConferencia:'Conferência demonstrativa'});
 if(code===2090){t.servicos.forEach(function(s){definirMob('situacaoServico___'+s.__indice,'cancelado');definirMob('referenciaServico___'+s.__indice,'CANCELAMENTO-FICTÍCIO-'+s.__indice);});fill({motivoCancelamento:'Cancelamento demonstrativo',referenciaCancelamento:'TRATAMENTO-FICTÍCIO'});}
 atualizarTelaMob();avisoMob('Etapa preenchida com dados fictícios. Revise e simule o avanço.');
}
function validarDemoMob(advance){
 if(DemoMobilidade.inspecao){avisoMob('Inspeção livre: não é possível avançar. Carregue um exemplo para executar a simulação.');return;}
 try{var code=codigoMob(),ctx={dados:dadosMob(),tabelas:tabelasMob()},next=MobilidadeRegras.proxima(code,ctx.dados,ctx.tabelas,MobilidadeConfig);beforeSendValidate(code,next);if(advance){MobilidadeServidor.atualizar(code,ctx,definirMob);DemoMobilidade.trilha.push({origem:code,destino:next});etapaDemoMob(next,false);inspecionarDemoMob(next);avisoMob('Transição simulada para #'+next+'.');}else avisoMob('Etapa válida. Destino: #'+next+'.');}catch(e){avisoMob(e.message||e);}
}
function tecnicoDemoMob(){var type=valorMob('fonteTecnicaMob'),content;if(type==='configuracao')content=JSON.stringify(MobilidadeConfig,null,2);else if(type==='datasets')content=JSON.stringify(MobilidadeConfig.dados,null,2);else if(type==='variaveis')content=JSON.stringify({contexto:MobilidadeContexto,dados:dadosMob(),tabelas:tabelasMob(),trilha:DemoMobilidade.trilha},null,2);else content=FontesMobilidade[type]||'';campoMob('conteudoTecnicoMob').textContent=content;}
function baixarDemoMob(name,text,type){var blob=new Blob([text],{type:type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
document.addEventListener('DOMContentLoaded',function(){
 document.querySelectorAll('[data-aba]').forEach(function(b){b.addEventListener('click',function(){abaDemoMob(b.dataset.aba);});});
 campoMob('carregarExemploMob').addEventListener('click',carregarDemoMob);campoMob('reiniciarMob').addEventListener('click',reiniciarDemoMob);campoMob('prepararEtapaMob').addEventListener('click',prepararDemoMob);campoMob('validarEtapaMob').addEventListener('click',function(){validarDemoMob(false);});campoMob('avancarEtapaMob').addEventListener('click',function(){validarDemoMob(true);});
 campoMob('imprimirMob').addEventListener('click',function(){abaDemoMob('formulario');document.querySelectorAll('[data-painel]').forEach(function(p){p.open=true;});window.print();});campoMob('exportarMob').addEventListener('click',function(){baixarDemoMob('cenario-mobilidade-ficticio.json',JSON.stringify({atividade:DemoMobilidade.atividade,dados:dadosMob(),tabelas:tabelasMob(),trilha:DemoMobilidade.trilha},null,2),'application/json');});
 campoMob('exportarCsvMob').addEventListener('click',function(){var cols=MobilidadeConfig.tabelas.despesas.campos,rows=tabelasMob().despesas,quote=function(v){var text=String(v||'');if(/^[=+\-@\t\r]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';};baixarDemoMob('despesas-mobilidade-ficticias.csv','\uFEFF'+[cols.map(quote).join(';')].concat(rows.map(function(row){return cols.map(function(c){return quote(row[c]);}).join(';');})).join('\r\n'),'text/csv;charset=utf-8');});
 var select=campoMob('inspecionarEtapaMob');MobilidadeConfig.processo.etapas.forEach(function(e){select.add(new Option('#'+e.codigo+' · '+e.nome,e.codigo));});select.addEventListener('change',function(){inspecionarDemoMob(this.value);});campoMob('inspecionarNoFormularioMob').addEventListener('click',function(){etapaDemoMob(DemoMobilidade.selecionada,true);abaDemoMob('formulario');avisoMob('Inspeção livre de campos. Essa ação não executa nem aprova uma etapa.');});
 document.querySelectorAll('.mob-node').forEach(function(n){var inspect=function(){var code=Number(n.dataset.atividade);if(code===0)code=1100;inspecionarDemoMob(code);};n.addEventListener('click',inspect);n.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect();}});});
 campoMob('zoomModeloMob').addEventListener('input',function(){var value=Math.max(50,Math.min(200,Number(this.value)||100));campoMob('viewportModeloMob').querySelector('svg').style.width=value+'%';});
 campoMob('fonteTecnicaMob').addEventListener('change',tecnicoDemoMob);campoMob('copiarTecnicoMob').addEventListener('click',function(){var text=campoMob('conteudoTecnicoMob').textContent;if(navigator.clipboard)navigator.clipboard.writeText(text).catch(function(){avisoMob('Selecione o conteúdo para copiar manualmente.');});else {var range=document.createRange();range.selectNodeContents(campoMob('conteudoTecnicoMob'));window.getSelection().removeAllRanges();window.getSelection().addRange(range);}});
 reiniciarDemoMob();abaDemoMob('formulario');
});
