module.exports=(cfg,write)=>{
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
 const control=(spec,id=spec.nome,name=id)=>{
  const cat=spec.tipo.startsWith('catalogo');const options=spec.opcoes||{};
  return `<div class="mob-field${spec.tipo==='textarea'?' mob-wide':''}"><label for="${id}">${esc(spec.rotulo)}</label>${spec.tipo==='textarea'?`<textarea id="${id}" name="${name}" rows="3" class="mob-control"></textarea>`:spec.tipo==='select'||cat?`<select id="${id}" name="${name}" class="mob-control"${cat?` data-catalogo="${spec.tipo}"`:''}><option value="">Selecione...</option>${Object.entries(options).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('')}</select>`:`<input id="${id}" name="${name}" class="mob-control" type="${spec.tipo}"${spec.tipo==='number'?' min="0" step="any"':''}>`}</div>`;
 };
 const seen=new Set();const stages=cfg.processo.etapas.map(e=>{
  const campos=e.campos.filter(c=>{if(seen.has(c.nome))return false;seen.add(c.nome);return true;});
  let extra='';
  if(e.codigo===1800||e.codigo===1900){const prefix=e.codigo===1800?'inspecao_':'retorno_';extra=`<div data-checklist="${prefix}" class="mob-grid">${cfg.seguranca.itens.map(c=>control({nome:prefix+c.codigo,rotulo:c.rotulo+(c.critico?' · crítico':''),tipo:'select',opcoes:{conforme:'Conforme',naoConforme:'Não conforme'}})).join('')}</div>`;}
  return `<details class="mob-panel" data-painel="${e.codigo}"${e.codigo===1100?' open':''}><summary><span>#${e.codigo}</span><strong>${e.nome}</strong><small>${e.papel}</small></summary><div class="mob-panel-body"><div class="mob-grid">${campos.map(c=>control(c)).join('')}</div>${extra}</div></details>`;
 }).join('\n');
 const sections=Object.entries(cfg.tabelas).map(([key,spec])=>{
  let input='';
  if(key==='participantes')input=control({nome:'participante',rotulo:'Colaborador participante',tipo:'catalogoPessoas'},'entrada_participante');
  if(key==='servicos'){
   input=control({nome:'codigoServico',rotulo:'Serviço',tipo:'select',opcoes:Object.fromEntries(cfg.servicos.map(s=>[s.codigoServico,s.nomeServico]))},'entrada_codigoServico');
   input+=[{nome:'inicioServico',rotulo:'Início do serviço',tipo:'datetime-local'},{nome:'fimServico',rotulo:'Fim do serviço',tipo:'datetime-local'},{nome:'quantidadeServico',rotulo:'Quantidade',tipo:'number'},{nome:'valorPrevistoServico',rotulo:'Valor total previsto na moeda do processo',tipo:'text'},{nome:'detalhesServico',rotulo:'Detalhes / finalidade',tipo:'textarea'}].map(c=>control(c,'entrada_'+c.nome)).join('');
   const extra=Object.fromEntries(cfg.servicos.flatMap(s=>s.campos).map(c=>[c.nome,c]));input+=Object.values(extra).map(c=>`<div data-servico-detalhe="${c.nome}" hidden>${control(c,'entrada_'+c.nome)}</div>`).join('');
  }
  if(key==='despesas')input=[{nome:'categoriaDespesa',rotulo:'Categoria',tipo:'select',opcoes:Object.fromEntries(cfg.servicos.map(s=>[s.codigoServico,s.nomeServico]).concat([['taxaCancelamento','Taxa de cancelamento']]))},{nome:'dataDespesa',rotulo:'Data da despesa',tipo:'date'},{nome:'descricaoDespesa',rotulo:'Descrição',tipo:'text'},{nome:'valorDespesa',rotulo:'Valor na moeda do processo',tipo:'text'},{nome:'formaCusteio',rotulo:'Pago por',tipo:'select',opcoes:{colaborador:'Beneficiário',empresa:'Cliente / organização'}},{nome:'referenciaComprovante',rotulo:'Referência do comprovante',tipo:'text'}].map(c=>control(c,'entrada_'+c.nome)).join('');
  if(key==='abastecimentos')input=[{nome:'dataHoraAbastecimento',rotulo:'Data e hora',tipo:'datetime-local'},{nome:'odometroAbastecimento',rotulo:'Odômetro no abastecimento',tipo:'number'},{nome:'tipoCombustivel',rotulo:'Combustível',tipo:'select',opcoes:{gasolina:'Gasolina',diesel:'Diesel',etanol:'Etanol'}},{nome:'litros',rotulo:'Litros (até 3 casas decimais)',tipo:'text'},{nome:'valorAbastecimento',rotulo:'Valor na moeda do processo',tipo:'text'},{nome:'postoAbastecimento',rotulo:'Posto',tipo:'text'},{nome:'referenciaAbastecimento',rotulo:'Referência do comprovante',tipo:'text'}].map(c=>control(c,'entrada_'+c.nome)).join('');
  const table=`<div class="mob-table-scroll"><table id="${spec.nome}" tablename="${spec.nome}" noaddbutton="true" nodeletebutton="true"><caption>${spec.rotulo} <span data-total="${key}">0</span></caption><thead><tr>${spec.visiveis.map(c=>`<th>${esc(spec.rotulos[c]||c)}</th>`).join('')}<th>Ações</th></tr></thead><tbody><tr>${spec.visiveis.map((c,i)=>`<td>${i===0?spec.campos.filter(k=>!spec.visiveis.includes(k)).map(k=>`<input type="hidden" id="${k}" name="${k}">`).join(''):''}${c==='situacaoServico'?`<select id="${c}" name="${c}" class="mob-control"><option value="pendente">Pendente</option><option value="confirmado">Confirmado</option><option value="cancelado">Cancelado</option></select>`:`<input id="${c}" name="${c}" class="mob-control" type="text">`}</td>`).join('')}<td>${key==='servicos'?'<details data-detalhes-reserva><summary>Ver detalhes</summary><dl></dl></details>':''}<button type="button" class="mob-button mob-danger" data-remover="${key}" onclick="removerLinhaMob('${key}',this)">Remover</button></td></tr></tbody></table></div>`;
  return `<section class="mob-panel" data-tabela-painel="${key}"><header class="mob-section-heading"><h2>${spec.rotulo}</h2></header><div class="mob-panel-body"><div data-compositor="${key}"><div class="mob-grid">${input}</div><button type="button" class="mob-button" data-adicionar="${key}">Adicionar</button></div>${table}</div></section>`;
 }).join('\n');
 const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${cfg.processo.nome}</title><link rel="stylesheet" href="/style-guide/css/fluig-style-guide.min.css"><script src="/portal/resources/js/jquery/jquery.js"></script><script src="/webdesk/vcXMLRPC.js"></script><link rel="stylesheet" href="css/mobilidade.css"><script src="js/configuracao.js"></script><script src="js/regrasMobilidade.js"></script><script src="js/contratos.js"></script><script src="js/interfaceMobilidade.js"></script></head><body><main class="fluig-style-guide mob-page" id="paginaMobilidade"><header class="mob-hero"><div class="mob-kicker">LETÍCIA SILVA · MOBILIDADE CORPORATIVA</div><h1>${cfg.processo.nome}</h1><p>Planejamento, reservas, segurança do veículo e prestação de contas em um processo.</p><button type="button" class="mob-button mob-secondary" id="telaCheiaMob">Apresentar em tela cheia</button></header><nav class="mob-etapas" aria-label="Fases do processo">${['Preparação','Aprovações','Organização','Veículo','Retorno','Financeiro'].map((f,i)=>`<div data-fase="${f}"><b>${i+1}</b>${f}</div>`).join('')}</nav><p class="mob-notice">Portfólio com dados fictícios. As reservas, transferências e liberações da demonstração são simuladas.</p><aside class="mob-norma"><strong>Verificação obrigatória antes de liberar o veículo</strong><p>${esc(cfg.seguranca.textoObrigatorio)}</p><p>${esc(cfg.seguranca.combustivelRetorno)}</p>${cfg.seguranca.referencias.map(r=>`<a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.nome}</a>`).join(' · ')}</aside><p id="mensagemMob" class="mob-message" role="status" aria-live="polite"></p><section class="mob-resumo" aria-label="Resumo de custos"><div>Previsto em BRL<strong id="totalPrevistoMob">R$ 0,00</strong></div><div>Cotado em BRL<strong id="totalCotadoMob">Aguardando cotações</strong></div><div>Reembolso<strong id="reembolsoMob">R$ 0,00</strong></div><div>Devolução de saldo<strong id="devolucaoMob">R$ 0,00</strong></div></section><form id="formMobilidade" name="formMobilidade">${cfg.automaticos.map(k=>`<input type="hidden" id="${k}" name="${k}">`).join('')}${stages}${sections}</form><footer>Desenvolvido por Letícia Silva · Dados fictícios · Base normativa documentada</footer></main></body></html>\n`;
 write('formulario/gestaoDeslocamentosCorporativos.html',html);
};
