module.exports=(cfg,write)=>{
 const p=cfg.processo,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'})[c]);
 const nodes=[{id:'Evento_0',codigo:0,nome:'Início',tipo:'startEvent',x:390,y:25,w:36,h:36}];
 p.etapas.forEach((e,i)=>{nodes.push({id:`Atividade_${e.codigo}`,codigo:e.codigo,nome:e.nome,papel:e.papel,tipo:'userTask',x:280,y:105+i*180,w:255,h:65});if(e.gateway)nodes.push({id:`Gateway_${e.gateway}`,codigo:e.gateway,nome:'Decisão',tipo:'exclusiveGateway',x:384,y:192+i*180,w:48,h:48});});
 Object.entries(p.encerramentos).forEach(([key,code],i)=>nodes.push({id:`Evento_${code}`,codigo:code,nome:{CONCLUIDO:'Concluído',CANCELADO:'Cancelado',RECUSADO:'Recusado'}[key],tipo:'endEvent',x:665+i*110,y:160+i*90,w:36,h:36}));
 const by=Object.fromEntries(nodes.map(n=>[n.id,n]));const target=code=>nodes.find(n=>n.codigo===code).id;
 const edges=[];const add=(source,to,label,route)=>{const a=by[source],b=by[to];let pts;
   if(b.y>a.y&&Math.abs(b.x-a.x)<150)pts=[[a.x+a.w/2,a.y+a.h],[b.x+b.w/2,b.y]];
   else {const lane=b.x>600?b.x+18:45+(edges.length%7)*26;pts=[[a.x,a.y+a.h/2],[lane,a.y+a.h/2],[lane,b.y+b.h/2],[b.x,b.y+b.h/2]];}
   edges.push({id:`Caminho_${edges.length+1}`,source,target:to,label,route,pts});};
 add('Evento_0','Atividade_1100','Iniciar');
 p.etapas.forEach(e=>{const task=`Atividade_${e.codigo}`,source=e.gateway?`Gateway_${e.gateway}`:task;if(e.gateway)add(task,source,'');e.rotas.forEach(r=>add(source,target(r.destino),r.valor+(r.quando==='sempre'?'':' · '+r.quando),{origem:e.codigo,gateway:e.gateway||null,campo:e.campoDecisao,...r}));});
 const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mob="https://github.com/leticiazooe/fluig-portfolio-gestao-deslocamentos-corporativos/modelo" id="DefinicoesMobilidade" targetNamespace="https://github.com/leticiazooe/fluig-portfolio-gestao-deslocamentos-corporativos"><bpmn:process id="${p.processoId}" name="${esc(p.nome)}" isExecutable="false"><bpmn:documentation>Modelo independente de portfólio. Base brasileira: CTB art.27 e Resolução CONTRAN 993/2023 conforme aplicabilidade. Retorno de combustível é política interna. Não é exportação nativa do Fluig.</bpmn:documentation>
${nodes.map(n=>`<bpmn:${n.tipo} id="${n.id}" name="${esc(n.nome)}"><bpmn:extensionElements><mob:atividade codigo="${n.codigo}"${n.papel?` papel="${esc(n.papel)}"`:''}/></bpmn:extensionElements>${edges.filter(e=>e.target===n.id).map(e=>`<bpmn:incoming>${e.id}</bpmn:incoming>`).join('')}${edges.filter(e=>e.source===n.id).map(e=>`<bpmn:outgoing>${e.id}</bpmn:outgoing>`).join('')}</bpmn:${n.tipo}>`).join('\n')}
${edges.map(e=>`<bpmn:sequenceFlow id="${e.id}" sourceRef="${e.source}" targetRef="${e.target}" name="${esc(e.label)}">${e.route?`<bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">${esc(`Number(hAPI.getCardValue("destinoMobilidade")) === ${e.route.destino}`)}</bpmn:conditionExpression>`:''}</bpmn:sequenceFlow>`).join('\n')}</bpmn:process><bpmndi:BPMNDiagram id="DiagramaMobilidade"><bpmndi:BPMNPlane id="PlanoMobilidade" bpmnElement="${p.processoId}">${nodes.map(n=>`<bpmndi:BPMNShape id="Shape_${n.id}" bpmnElement="${n.id}"><dc:Bounds x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}"/></bpmndi:BPMNShape>`).join('')}${edges.map(e=>`<bpmndi:BPMNEdge id="Edge_${e.id}" bpmnElement="${e.id}">${e.pts.map(([x,y])=>`<di:waypoint x="${x}" y="${y}"/>`).join('')}</bpmndi:BPMNEdge>`).join('')}</bpmndi:BPMNPlane></bpmndi:BPMNDiagram></bpmn:definitions>\n`;
 write('processo/gestaoDeslocamentosCorporativos.bpmn',xml);
 write('processo/roteamento.json',JSON.stringify(edges.filter(e=>e.route).map(e=>({...e.route,expressaoFluig:`Number(hAPI.getCardValue("destinoMobilidade")) === ${e.route.destino}`})),null,2)+'\n');
 write('processo/gestaoDeslocamentosCorporativos.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1050 ${p.etapas.length*180+230}" role="img" aria-labelledby="tituloModelo"><title id="tituloModelo">Gestão de deslocamentos: aprovações, organização, inspeção, retorno e contas</title><defs><marker id="setaModelo" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="#648092"/></marker></defs><style>text{font:12px Arial,sans-serif;fill:#173c54}.mob-node{cursor:pointer}.mob-node rect,.mob-node circle,.mob-node polygon{fill:white;stroke:#51778b;stroke-width:2}.mob-node.is-current rect,.mob-node.is-current circle{fill:#dceefb;stroke:#176ba0;stroke-width:4}.mob-node.is-executed rect{fill:#e6f5ee}.mob-edge.is-executed{stroke:#158261;stroke-width:3}</style>${edges.map(e=>`<polyline class="mob-edge" data-caminho="${e.id}" data-origem="${e.route?e.route.origem:by[e.source].codigo}" data-destino="${e.route?e.route.destino:by[e.target].codigo}" points="${e.pts.map(a=>a.join(',')).join(' ')}" fill="none" stroke="#b6c6cf" stroke-width="1" marker-end="url(#setaModelo)"/>`).join('')}${nodes.map(n=>`<g class="mob-node" data-atividade="${n.codigo}" tabindex="0" role="button" aria-label="${esc(n.nome)} ${n.codigo}">${n.tipo==='userTask'?`<rect x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="10"/><text x="${n.x+14}" y="${n.y+25}">${esc(n.nome)}</text><text x="${n.x+14}" y="${n.y+49}" style="font-size:11px">#${n.codigo} · ${esc(n.papel)}</text>`:n.tipo==='exclusiveGateway'?`<polygon points="${n.x+24},${n.y} ${n.x+48},${n.y+24} ${n.x+24},${n.y+48} ${n.x},${n.y+24}"/><text x="${n.x+19}" y="${n.y+29}">×</text>`:`<circle cx="${n.x+18}" cy="${n.y+18}" r="18"${n.tipo==='endEvent'?' style="stroke-width:4"':''}/><text x="${n.x-10}" y="${n.y+60}">${esc(n.nome)} #${n.codigo}</text>`}</g>`).join('')}</svg>\n`);
};
